### ISSUE TITLE
Tomorrow Night & Monokai Theme Hide Execute Selection Bounding Box

### ISSUE THREAD

**Issue by KeeonTabrizi** [darekkay/config-files#1]
This is an issue I have noticed only in the tomorrow night / monokai themes. I have not experienced this issue with other themes so I think it may be isolated to these themes.

- https://github.com/darekkay/config-files/blob/master/intellij-idea/config/colors/dk-tomorrow-night.icls
- https://darekkay.com/blog/monokai-theme-intellij/dk-monokai-142.jar 

Note that in IntelliJData Grip there is functionality that draws a bounding box around the statement the editor will execute (which can be selected manually or the editor will infer). Details can be seen here: https://www.jetbrains.com/datagrip/features/executing.html . Note the thin green bounding box around the query:

![Example](https://www.jetbrains.com/datagrip/features/img/console/ExecuteOptionsInAction.gif)

Static Image Example (Default Theme):

![image](https://user-images.githubusercontent.com/3408390/56325129-e7135980-6125-11e9-814e-5f3600786cbd.png)

However in Monokai / Tomorrow night the box disappears:

![image](https://user-images.githubusercontent.com/3408390/56325158-f7c3cf80-6125-11e9-9ca6-14be476afcf8.png)
![image](https://user-images.githubusercontent.com/3408390/56325162-fe524700-6125-11e9-9ffc-a2eafb1811a4.png)

I hope it's just a small setting I'm missing, but again I have not seen this behavior across many other imported themes.

**Comment by darekkay** [comment]
Thanks for the bug report and the detailed description!

The border can be configured here: `Database` → `Console` → `Statement to execute` (Effect: Bordered).

I've updated both themes to include a gray-ish border :)

**Comment by KeeonTabrizi** [comment]
Thank you!

**Comment by KeeonTabrizi** [comment]
For my version of datagrip the setting is actually in a different section:

![image](https://user-images.githubusercontent.com/3408390/58356743-3c314200-7e2d-11e9-97ab-b96c82635e09.png)

**Comment by darekkay** [comment]
I've just omitted the `Editor` → `Color Scheme` part ;) 
Your screenshot displays the same path as I've posted: (`Editor` → `Color Scheme` → ) `Database` → `Console` → `Statement to execute` (the last two parts are on the right side)
