### ISSUE TITLE
Dark Theme for notepad++ LogFile

### ISSUE THREAD

**Issue by harikesh409** [darekkay/config-files#2]
If we are using any dark theme the [logfile UDL ](https://github.com/darekkay/config-files/blob/master/notepad%2B%2B/lang_logfile.xml)is not looking good. If possible give an dark theme release for that style.

**Comment by darekkay** [comment]
I am not using a dark theme, hence I cannot provide it. But you can adjust all the colors in the `Language` →  `Define your language...` modal.
